---
title: 'Statistical analysis: A simple example'
author: "Shige Song"
output:
  html_document: default
  pdf_document:
    latex_engine: xelatex
    natbib: yes
  word_document: default
---

```{r setup, message=F, echo=F, warning=FALSE, tidy=F, results='hide'}
library(ggplot2)
library(ggthemes)
library(Zelig)
data(turnout)
```

Descriptive statistics
---------------------------------

I want to compare the racial difference in education, income, and voting behavior. Here is what I did: 

```{r pander, results='asis', message=FALSE, prompt=FALSE}
library(reshape2)
library(pander)
panderOptions('table.style', 'rmarkdown')
new <- melt(turnout, id=c("race", "age"))
newcast <- dcast(new, race ~ variable, mean)
pandoc.table(newcast, digits=3)
```

The table can be further polished, but it does the job. The point is that the *reshape2* package can transform the data into arbitrary format, which can then be converted into HTML table using the  *pander* package. 

```{r gmisc, results='asis', message=FALSE, prompt=FALSE, warning=FALSE}
library(stargazer)

newcast <- as.matrix(newcast)
rownames(newcast) <- NULL

stargazer(newcast, type="html")
```

The second table looks a lot nicer than the first one. 

Graphical exploration
---------------------------------
```{r ggplot, fig.show='asis'}
ggplot(turnout, aes(age, educate)) + geom_point(stat="identity") + theme_few()
```

Estimation
---------------------------------

```{r citation, echo=FALSE, message=FALSE}
library(knitcitations)
```

*[Zelig](http://projects.iq.harvard.edu/zelig)* is a powerful *R* package `r citep("10.1198/106186008X384898")`. It provides an unified interface to a large number of existing *R* packages for statistical estimation. In addition, it implements the powerful statistical simulation methodology proposed by `r citet("10.2307/2669316")`.

The package "*[texreg](http://cran.r-project.org/web/packages/texreg/index.html)*" has a function called ``htmlreg()'' that can be used to produce regression tables in R Markdown. Here is a simple example showing how "texreg" and "Zelig" can work together:

```{r zelig, message=F, echo=T, warning=FALSE, tidy=F, results='hide'}
library(Zelig)

data(turnout)

z.out1 <- zelig(vote ~ age, model = "logit", data = turnout)
z.out2 <- zelig(vote ~ age + race, model = "logit", data = turnout)
z.out3 <- zelig(vote ~ age + race + educate, model = "logit", data = turnout)
```
The "*texreg*" package is very powerful and flexible. I also like the "*[stargazer](http://cran.r-project.org/web/packages/stargazer/index.html)*" package but, unfortunately, it does not produce html code so it cannot be used here. 

```{r texreg, results='asis', message=FALSE, echo=T, warning=FALSE}
library(texreg)
htmlreg(list(z.out1, z.out2, z.out3), center=T, single.row=T, caption="", star.symbol = "\\*")
```

```{r, results='asis', message=FALSE, echo=FALSE}
stargazer(z.out1, z.out2, z.out3, type="html", model.number=F)
```


Statistical simulation
--------------------------------

Here are some simulation results:

```{r simulation, results='hide'}
x.out2 <- setx(z.out2, age = 36, race = "white")
x.out2
s.out2 <- sim(z.out2, x = x.out2)
```

```{r plot_simulation, results='asis'}
plot(s.out2)
```

Now what do these figures show?

Of course, you also need *[R](http://www.r-project.org/)*, *[Rstudio](http://www.rstudio.com/)*, *[knitr](http://yihui.name/knitr/)*, *[ggplot2](http://ggplot2.org/)*, *[ggthemes](https://github.com/jrnold/ggthemes)*, *[pander](http://rapporter.github.io/pander/)*, *[Gmisc](http://gforge.se/gmisc/)*, and *[knitcitations](https://github.com/cboettig/knitcitations)*, which are all *free*. The source file can be found from [GitHub](https://github.com/shigesong/famine_project/blob/master/test_markdown.Rmd). 


REFERENCES
-------------------------

```{r bibliography, results='asis', message=FALSE, echo=FALSE}
bibliography()
```
